name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main # ou 'master', dependendo da sua branch principal

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --configuration production

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
            folder: dist/bastiao-web/browser # PASTA CORRETA NO ANGULAR 18
            branch: gh-pages # Branch que armazenará os arquivos compilados

      - name: Copy index.html to 404.html for Angular routing
        run: cp dist/bastiao-web/browser/index.html dist/bastiao-web/browser/404.html